language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=15
  - DJANGO=16
  - DJANGO=17
  - DJANGO=18
  - DJANGO=19
  - DJANGO=110
  - DJANGO=111

install:
  - pip install tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}-django${DJANGO}

script:
    - tox -e ${TOXENV}

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.3
    - python: 3.3
      env: DJANGO=1.4
    - python: 3.3
      env: DJANGO=1.5
    - python: 3.3
      env: DJANGO=1.6
    - python: 3.3
      env: DJANGO=1.7
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.3
      env: DJANGO=1.10
    - python: 3.3
      env: DJANGO=1.11
    - python: 3.4
      env: DJANGO=1.3
    - python: 3.4
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.5
    - python: 3.4
      env: DJANGO=1.6
    - python: 3.4
      env: DJANGO=1.7
    - python: 3.5
      env: DJANGO=1.3
    - python: 3.5
      env: DJANGO=1.4
    - python: 3.5
      env: DJANGO=1.5
    - python: 3.5
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.7
    - python: 3.6
      env: DJANGO=1.3
    - python: 3.6
      env: DJANGO=1.4
    - python: 3.6
      env: DJANGO=1.5
    - python: 3.6
      env: DJANGO=1.6
    - python: 3.6
      env: DJANGO=1.7
